### ISSUE TITLE
Displaying only 1 group

### ISSUE THREAD

**Issue by bem26388** [justineuro/sdRplot#3]
Hi there,

I am now trying to display solely on group in the profile. I am having problems with this issue. Does your code also work with only one group?

Thanks a lot, cheers
Barbara

**Comment by justineuro** [comment]
Hi Barbara,

I have updated the code for `sdRplot.R` to accomodate plots for only one profile.  
After sourcing this updated file, the following set of codes:
```r
###
# Example 2 (for grp1means only)
###
low<-c("Serious","Slow","Useless","Tiring","Old","Hard","Long")
high<-c("Fun","Fast","Useful","Light","New","Easy","Short")
scale<-c("SA","A","N","A","SA")
grp1means<-c(4.2,4.6,4.3,4.1,4.5,4.5,4.0)
data1grp<-matrix(
  cbind(low,high,grp1means),
  nrow=7,ncol=3,byrow=FALSE,
  dimnames=list(c("I1","I2","I3","I4","I5","I6","I7"),
                c("Low","High","Grp1"))
)
sdRplot(5,scale,7,data1grp)
```
will yield the following SD plot:
![barb-n1](https://user-images.githubusercontent.com/7970053/103807945-29b35d00-5092-11eb-8cef-dbaef94352f3.png)

Hoping this will help.

Thanks for bringing this point for improvement to my attention.

Best,
Justine Leon

**Comment by bem26388** [comment]
Hi Justin,

thank you so much! Just tried it out with my data, it worked out perfectly fine!
Thanks a bunch!

Cheers
